# CircleCI is used exclusively to test code formatting.
# Thus ObsPy does not even have to be installed.
version: 2
jobs:
  build:
    docker:
      - image: continuumio/anaconda:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            conda create -n test-env
            conda activate test-env
            conda install -y flake8 pep8-naming

      - run:
          name: run linting
          command: |
            conda activate test-env
            flake8 --version
            flake8 --verbose --ignore=E402,$(python -c 'import pycodestyle; print(pycodestyle.DEFAULT_IGNORE)') --exclude=__init__.py obspy
