name: "Docs building"
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: obspy/sphinx-action@master
        with:
          pre-build-command: "python -m pip install ."
          docs-folder: "misc/docs/"
      - run: tar cfJ documentation.tar.xz misc/docs/build/html/
      - uses: actions/upload-artifact@v2
        with:
          name: DocumentationHTML
          path: documentation.tar.xz
