name: "Docs building"
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: "apt-get update -yqq && apt-get install -yqq --no-install-recommends build-essential gcc"
          docs-folder: "misc/docs/"