name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            workdir: [misc/docker/base_images/ubuntu_18_04_bionic_32bit, misc/docker/base_images/ubuntu_18_04_bionic]
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: heavelock/obspy-testing
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ${{ matrix.workdir }}
        # tag_names: true