name: validate
on: pull_request

jobs:
  # Simply applies flake8 to the codebase
  lint_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          python-version: 3.7

      - name: install linting packages
        run: pip install flake8

      - name: flake8
        run: flake8 .

  # Runs the tests on combinations of the supported python/os matrix.
  test_code:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v1

      - name: Setup conda
        uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}
          activate-environment: test
          environment-file: .github/test_conda_env.yml
          condarc-file: .github/test_condarc.yml

      - name: install obspy in dev mode
        shell: bash -l {0}
        run: |
          pip install -e .

      - name: print package info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: run test suite
        shell: bash -l {0}
        run: |
          obspy-runtests --report


# This is a very useful step for debugging, it allows you to ssh into the CI
# machine (https://github.com/marketplace/actions/debugging-with-tmate).
# Make sure to open the log before the job starts else you cant see the tmate
# url. See https://github.com/mxschmitt/action-tmate/issues/1.
# Also, the CI machine will close on a non-zero exit code (annoying). This can
# be overcome by coalescing the null command like so:
# $ some-command-that-can-fail || :
#
#- name: Setup tmate session
#  uses: mxschmitt/action-tmate@v1
